# Generated by Django 5.0.6 on 2024-06-28 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.IntegerField()),
                ('role', models.CharField(null=True)),
            ],
            options={
                'ordering': ['idx'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_oral', models.BooleanField()),
                ('number', models.IntegerField()),
                ('title', models.CharField(null=True)),
                ('akn', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('raw', models.CharField()),
                ('identifier', models.CharField(unique=True)),
                ('title', models.JSONField(default=list)),
                ('area', models.CharField(null=True)),
                ('role', models.CharField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnswerContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.IntegerField()),
                ('type', models.CharField()),
                ('value', models.TextField()),
                ('image', models.TextField(null=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='content_list', to='legisweb_viewer.answer')),
            ],
            options={
                'ordering': ['idx'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InquiryList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.IntegerField()),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inquiries', to='legisweb_viewer.inquiry')),
            ],
            options={
                'ordering': ['idx'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InquiryContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.IntegerField()),
                ('type', models.CharField()),
                ('value', models.TextField()),
                ('image', models.TextField(null=True)),
                ('container_list', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='content_list', to='legisweb_viewer.inquirylist')),
            ],
            options={
                'ordering': ['idx'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='inquiry',
            name='inquirer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inquirers', related_query_name='inquirer', to='legisweb_viewer.person'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='respondent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respondents', related_query_name='respondent', to='legisweb_viewer.person'),
        ),
        migrations.CreateModel(
            name='Hansard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('akn', models.TextField()),
                ('absent', models.ManyToManyField(related_name='hansard_absents', related_query_name='hansard_absent', to='legisweb_viewer.person')),
                ('guest', models.ManyToManyField(related_name='hansard_guests', related_query_name='hansard_guest', to='legisweb_viewer.person')),
                ('officer', models.ManyToManyField(related_name='hansard_officers', related_query_name='hansard_officer', to='legisweb_viewer.person')),
                ('present', models.ManyToManyField(related_name='hansard_presents', related_query_name='hansard_present', to='legisweb_viewer.person')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='respondent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='legisweb_viewer.person'),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.IntegerField()),
                ('role', models.CharField(null=True)),
                ('is_oral', models.BooleanField()),
                ('inquirer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='legisweb_viewer.person')),
            ],
            options={
                'ordering': ['idx'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.IntegerField()),
                ('type', models.CharField()),
                ('value', models.TextField()),
                ('image', models.TextField(null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='content_list', to='legisweb_viewer.question')),
            ],
            options={
                'ordering': ['idx'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.IntegerField()),
                ('hansard', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='legisweb_viewer.hansard')),
            ],
            options={
                'ordering': ['idx'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='question',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='legisweb_viewer.questionsession'),
        ),
        migrations.AddField(
            model_name='answer',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='legisweb_viewer.questionsession'),
        ),
        migrations.CreateModel(
            name='RespondList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.IntegerField()),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responds', to='legisweb_viewer.inquiry')),
            ],
            options={
                'ordering': ['idx'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RespondContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.IntegerField()),
                ('type', models.CharField()),
                ('value', models.TextField()),
                ('image', models.TextField(null=True)),
                ('container_list', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='content_list', to='legisweb_viewer.respondlist')),
            ],
            options={
                'ordering': ['idx'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Speech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.IntegerField()),
                ('role', models.CharField(null=True)),
                ('by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='legisweb_viewer.person')),
                ('hansard', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='speeches', to='legisweb_viewer.hansard')),
            ],
            options={
                'ordering': ['idx'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpeechContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.IntegerField()),
                ('type', models.CharField()),
                ('value', models.TextField()),
                ('image', models.TextField(null=True)),
                ('speech', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='content_list', to='legisweb_viewer.speech')),
            ],
            options={
                'ordering': ['idx'],
                'abstract': False,
            },
        ),
    ]
